server:
  port: 9020

logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: ${LOG_PATH:logs/auth-service.log}
    path: ${LOG_PATH:logs/auth-service.log}

spring:
  application:
    name: UserService

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://rajsubhod:raj%40password@userdetails.r4rme.mongodb.net/userservice?retryWrites=true&w=majority&appName=userdetails}
      password: ${MONGO_PASSWORD:password}
      username: ${MONGO_USERNAME:rajsubhod}
      database: ${MONGO_DATABASE:userservice}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}


  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.rajsubhod.userservice.deserializer.UserInfoDeserializer
      group-id: ${KAFKA_GROUP_ID:1}
      auto-offset-reset: earliest
    topic:
        name: ${KAFKA_TOPIC_NAME:auth}
